### ISSUE TITLE
Issue when i try to `mine cuda`

### ISSUE THREAD

**Issue by GeoffedUP** [0xMithril/COSMiC-v3-0xMTH#3]
when i set my contract address and my account address and try to use cmd `mine cuda`

I get this...
```[21:39:07.826] Error: Couldn't decode uint256 from ABI: 0x
    at SolidityTypeUInt.formatOutputUInt [as _outputFormatter] (C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-eth-abi\src\formatters.js:0:0)
    at SolidityTypeUInt.SolidityType.decode (C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-eth-abi\src\type.js:0:0)
    at C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-eth-abi\src\index.js:0:0
    at Array.forEach (<anonymous>)
    at ABICoder.decodeParameters (C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-eth-abi\src\index.js:0:0)
    at Contract._decodeMethodReturn (C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-eth-contract\src\index.js:0:0)
    at Method.outputFormatter (C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-eth-contract\src\index.js:0:0)
    at Method.formatOutput (C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-core-method\src\index.js:0:0)
    at sendTxCallback (C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-core-method\src\index.js:0:0)
    at C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-core-requestmanager\src\index.js:0:0
    at XMLHttpRequest.HttpProvider.send.request.onreadystatechange (C:\snapshot\COSMiC-v3-0xMTH\node_modules\web3-providers-http\src\index.js:0:0)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\snapshot\COSMiC-v3-0xMTH\node_modules\xhr2\lib\xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (C:\snapshot\COSMiC-v3-0xMTH\node_modules\xhr2\lib\xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (C:\snapshot\COSMiC-v3-0xMTH\node_modules\xhr2\lib\xhr2.js:509:12)
    at IncomingMessage.<anonymous> (C:\snapshot\COSMiC-v3-0xMTH\node_modules\xhr2\lib\xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

bugged u enough tonight so i posted here didn't want disturb you haha 😆

**Comment by GeoffedUP** [comment]
Never mind I didn't have the right web3provider address 👍

**Comment by GeoffedUP** [comment]
Never mind I didn't have the right web3provider address 👍
